//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class dives {
    
    private string unitsField;
    
    private string schemaField;
    
    private divesDive diveField;
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public string schema {
        get {
            return this.schemaField;
        }
        set {
            this.schemaField = value;
        }
    }
    
    /// <remarks/>
    public divesDive dive {
        get {
            return this.diveField;
        }
        set {
            this.diveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class divesDive {
    
    private string dateField;
    
    private string identifierField;
    
    private sbyte diveNumberField;
    
    private sbyte ratingField;
    
    private string countryField;
    
    private string locationField;
    
    private string siteField;
    
    private sbyte repetitiveDiveField;
    
    private float siteLatField;
    
    private float siteLonField;
    
    private string diverField;
    
    private string computerField;
    
    private int serialField;
    
    private float maxDepthField;
    
    private float averageDepthField;
    
    private float cnsField;
    
    private string decoModelField;
    
    private short durationField;
    
    private string gasModelField;
    
    private sbyte surfaceIntervalField;
    
    private sbyte sampleIntervalField;
    
    private float tempAirField;
    
    private float tempHighField;
    
    private float tempLowField;
    
    private string visibilityField;
    
    private string weatherField;
    
    private string weightField;
    
    private string notesField;
    
    private string diveMasterField;
    
    private string diveOperatorField;
    
    private string skipperField;
    
    private string boatField;
    
    private string tagsField;
    
    private string typesField;
    
    private string buddiesField;
    
    private divesDiveItem[] gearField;
    
    private divesDiveGases gasesField;
    
    private divesDiveSample[] samplesField;
    
    /// <remarks/>
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    public sbyte diveNumber {
        get {
            return this.diveNumberField;
        }
        set {
            this.diveNumberField = value;
        }
    }
    
    /// <remarks/>
    public sbyte rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public sbyte repetitiveDive {
        get {
            return this.repetitiveDiveField;
        }
        set {
            this.repetitiveDiveField = value;
        }
    }
    
    /// <remarks/>
    public float siteLat {
        get {
            return this.siteLatField;
        }
        set {
            this.siteLatField = value;
        }
    }
    
    /// <remarks/>
    public float siteLon {
        get {
            return this.siteLonField;
        }
        set {
            this.siteLonField = value;
        }
    }
    
    /// <remarks/>
    public string diver {
        get {
            return this.diverField;
        }
        set {
            this.diverField = value;
        }
    }
    
    /// <remarks/>
    public string computer {
        get {
            return this.computerField;
        }
        set {
            this.computerField = value;
        }
    }
    
    /// <remarks/>
    public int serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public float maxDepth {
        get {
            return this.maxDepthField;
        }
        set {
            this.maxDepthField = value;
        }
    }
    
    /// <remarks/>
    public float averageDepth {
        get {
            return this.averageDepthField;
        }
        set {
            this.averageDepthField = value;
        }
    }
    
    /// <remarks/>
    public float cns {
        get {
            return this.cnsField;
        }
        set {
            this.cnsField = value;
        }
    }
    
    /// <remarks/>
    public string decoModel {
        get {
            return this.decoModelField;
        }
        set {
            this.decoModelField = value;
        }
    }
    
    /// <remarks/>
    public short duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string gasModel {
        get {
            return this.gasModelField;
        }
        set {
            this.gasModelField = value;
        }
    }
    
    /// <remarks/>
    public sbyte surfaceInterval {
        get {
            return this.surfaceIntervalField;
        }
        set {
            this.surfaceIntervalField = value;
        }
    }
    
    /// <remarks/>
    public sbyte sampleInterval {
        get {
            return this.sampleIntervalField;
        }
        set {
            this.sampleIntervalField = value;
        }
    }
    
    /// <remarks/>
    public float tempAir {
        get {
            return this.tempAirField;
        }
        set {
            this.tempAirField = value;
        }
    }
    
    /// <remarks/>
    public float tempHigh {
        get {
            return this.tempHighField;
        }
        set {
            this.tempHighField = value;
        }
    }
    
    /// <remarks/>
    public float tempLow {
        get {
            return this.tempLowField;
        }
        set {
            this.tempLowField = value;
        }
    }
    
    /// <remarks/>
    public string visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <remarks/>
    public string weather {
        get {
            return this.weatherField;
        }
        set {
            this.weatherField = value;
        }
    }
    
    /// <remarks/>
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public string notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public string diveMaster {
        get {
            return this.diveMasterField;
        }
        set {
            this.diveMasterField = value;
        }
    }
    
    /// <remarks/>
    public string diveOperator {
        get {
            return this.diveOperatorField;
        }
        set {
            this.diveOperatorField = value;
        }
    }
    
    /// <remarks/>
    public string skipper {
        get {
            return this.skipperField;
        }
        set {
            this.skipperField = value;
        }
    }
    
    /// <remarks/>
    public string boat {
        get {
            return this.boatField;
        }
        set {
            this.boatField = value;
        }
    }
    
    /// <remarks/>
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public string types {
        get {
            return this.typesField;
        }
        set {
            this.typesField = value;
        }
    }
    
    /// <remarks/>
    public string buddies {
        get {
            return this.buddiesField;
        }
        set {
            this.buddiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public divesDiveItem[] gear {
        get {
            return this.gearField;
        }
        set {
            this.gearField = value;
        }
    }
    
    /// <remarks/>
    public divesDiveGases gases {
        get {
            return this.gasesField;
        }
        set {
            this.gasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("sample", IsNullable=false)]
    public divesDiveSample[] samples {
        get {
            return this.samplesField;
        }
        set {
            this.samplesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class divesDiveItem {
    
    private string typeField;
    
    private string manufacturerField;
    
    private string nameField;
    
    private string serialField;
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class divesDiveGases {
    
    private divesDiveGasesGas gasField;
    
    /// <remarks/>
    public divesDiveGasesGas gas {
        get {
            return this.gasField;
        }
        set {
            this.gasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class divesDiveGasesGas {
    
    private float pressureStartField;
    
    private float pressureEndField;
    
    private sbyte oxygenField;
    
    private sbyte heliumField;
    
    private sbyte doubleField;
    
    private sbyte tankSizeField;
    
    private short workingPressureField;
    
    private string supplyTypeField;
    
    private short durationField;
    
    private string tankNameField;
    
    /// <remarks/>
    public float pressureStart {
        get {
            return this.pressureStartField;
        }
        set {
            this.pressureStartField = value;
        }
    }
    
    /// <remarks/>
    public float pressureEnd {
        get {
            return this.pressureEndField;
        }
        set {
            this.pressureEndField = value;
        }
    }
    
    /// <remarks/>
    public sbyte oxygen {
        get {
            return this.oxygenField;
        }
        set {
            this.oxygenField = value;
        }
    }
    
    /// <remarks/>
    public sbyte helium {
        get {
            return this.heliumField;
        }
        set {
            this.heliumField = value;
        }
    }
    
    /// <remarks/>
    public sbyte @double {
        get {
            return this.doubleField;
        }
        set {
            this.doubleField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tankSize {
        get {
            return this.tankSizeField;
        }
        set {
            this.tankSizeField = value;
        }
    }
    
    /// <remarks/>
    public short workingPressure {
        get {
            return this.workingPressureField;
        }
        set {
            this.workingPressureField = value;
        }
    }
    
    /// <remarks/>
    public string supplyType {
        get {
            return this.supplyTypeField;
        }
        set {
            this.supplyTypeField = value;
        }
    }
    
    /// <remarks/>
    public short duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string tankName {
        get {
            return this.tankNameField;
        }
        set {
            this.tankNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class divesDiveSample {
    
    private short timeField;
    
    private float depthField;
    
    private float pressureField;
    
    private string alarmField;
    
    private string extraField;
    
    private float temperatureField;
    
    private float ppo2Field;
    
    private sbyte ndtField;
    
    /// <remarks/>
    public short time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public float depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    public float pressure {
        get {
            return this.pressureField;
        }
        set {
            this.pressureField = value;
        }
    }
    
    /// <remarks/>
    public string alarm {
        get {
            return this.alarmField;
        }
        set {
            this.alarmField = value;
        }
    }
    
    /// <remarks/>
    public string extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
    
    /// <remarks/>
    public float temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    public float ppo2 {
        get {
            return this.ppo2Field;
        }
        set {
            this.ppo2Field = value;
        }
    }
    
    /// <remarks/>
    public sbyte ndt {
        get {
            return this.ndtField;
        }
        set {
            this.ndtField = value;
        }
    }
}
